title: My Karistanian (میری کارستانیاں) 
author: Muhammad Adnan
email: adnan.mohib@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Science Student, Passionate about new technology, Researcher and a Developer.

# social links
twitter_username: @Adnan_Mohib9
github_username:  AdnanMuhib

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
